//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Barkod_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terazi
    {
        public int Id { get; set; }
        public Nullable<int> teraziOnEk { get; set; }
    }
}
